# Generated by Django 5.0.6 on 2024-05-12 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('RentalRate', models.TimeField()),
                ('Availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RentalStartDateTime', models.DateTimeField()),
                ('RentalEndDateTime', models.DateTimeField()),
                ('TotalCost', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental_system.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental_system.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField()),
                ('PaymentDateTime', models.DateTimeField()),
                ('PaymentMethod', models.CharField(choices=[('C', 'CASH'), ('O', 'ONLINE')], max_length=1)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle_rental_system.rental')),
            ],
        ),
    ]
