# Generated by Django 4.2.13 on 2024-05-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(default=1, upload_to='uploads/Vehicle/'),
            preserve_default=False,
        ),
    ]
