# Generated by Django 4.2.13 on 2024-06-14 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_system', '0005_customer_password_customer_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
