# Generated by Django 4.2.13 on 2024-06-15 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_system', '0006_remove_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
    ]
