# Generated by Django 4.2.13 on 2024-06-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_system', '0008_alter_rental_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='PaymentMethod',
        ),
    ]
