# Generated by Django 4.2.13 on 2024-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_system', '0009_remove_rental_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Esewa', 'Esewa')], default='Cash', max_length=20),
        ),
    ]
