# Generated by Django 4.2.13 on 2024-06-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_system', '0011_rental_status_alter_vehicle_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Expired', 'Expired'), ('Ongoing', 'Ongoing'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
