# Generated by Django 4.2.13 on 2024-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_rental_system', '0012_remove_rental_payment_method_alter_rental_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Expired', 'Expired'), ('Confirmed', 'Confirmed'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
